pipeline {
    agent any
    stages {
        stage('terraform') {
            steps {
                sh './terraform apply'
            }
        }
        stage('Build') {
            agent { dockerfile true }
            steps {
                // build project
                sh './app/mvnw clean package'
            }
        }
        stage('Test') {
            steps {
                //run tests
                sh './app/mvn test'
            }
        }
        stage('Deploy') { 
            steps {
                // deploy server
                sh './app/mvnw spring-boot:run'
            }
        }
    }
}